version: "3"

services:
  riemann:
    image: riemannio/riemann
    ports:
      - "5555:5555"
      - "5555:5555/udp"
      - "5556:5556"
    volumes:
      - ./riemann/riemann.config:/etc/riemann.config
    networks:
      - monitoring

  influxdb:
    image: influxdb:1.8
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=riemann
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
      - INFLUXDB_USER=riemann
      - INFLUXDB_USER_PASSWORD=riemann
    volumes:
      - influxdb_data:/var/lib/influxdb
    networks:
      - monitoring

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - influxdb
    networks:
      - monitoring

  agent:
    build: ./agent
    depends_on:
      - riemann
    networks:
      - monitoring
    deploy:
      replicas: 3

networks:
  monitoring:

volumes:
  influxdb_data:
  grafana_data:
